import Head from "next/head";
import Image from "next/image";
import { Content, Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GitHub, LinkedIn } from "@mui/icons-material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.jumbotron}>
        <h1>ZACH BARNES</h1>
        <h3>SOFTWARE ENGINEER</h3>
      </header>
      <main>
        <section className={styles.mainButtons}>
          <button>About</button>
          <button>Work</button>
          <button>Contact</button>
        </section>
        <section className={styles.secondaryButtons}>
          <button>
            <GitHub fontSize="large"/>
          </button>
          <button>
            <LinkedIn fontSize="large"/>
          </button>
        </section>
      </main>
      <footer className={styles.copyright}>
        <p>© Zach Barnes 2023.</p>
      </footer>
    </>
  );
}
